spring:
  application:
    name: ms-auth

  r2dbc:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8081
  
jwt:
  secret: MiClaveSuperSecretaParaJwtQueDebeTenerMasDe32Caracteres
  expiration: 86400000